travis:
  secure:
    BINSTAR_TOKEN: jkFqq6Wz1HBq2T++4vOS5RREm+xOdHALTwypBy2QoniorqzGKoiY+QHpEk8xj3Kj2CkOvgG6FUv3CfiMz+4sCLKhUETJmCHRsUw8MuS0KXECFC4mgnr9DsbLqm8OvQ79DBw8ck+Wxq2v/oBu0HQi5QQCBERESWTiXzf3HyPckngeRUb1YgEkm4SIXPdLebTpDqgK7x9C98VSnTQPExBxuXbFCcw/7SCRWTRLH2NLkjDAGVghpP/mTGvYuVc7cpL3iEf8uEMabQMmOW97y2P7fwZEte87nuqHgbkkcnr2ipgkoyamkGYsBActSKQTA/htJPrEdbFlk/61XB5zq30jeZIKrpr8e0oY1Kb22HA3vvIfU0lBq5lxpoWC9Ngo1bXLK32aEQl756YWdLb1uq90RK3xNQyaViePjTlBVcGUWkfGiTdPP/IcljPcXsw2dh6vVdeijpeE2ox6Rezzl5z1E3WeYwHEoXifD1CwNnD14FQu5zVhywpc/8fGLHDb4u6nOmCRs9euwQaetknb+aUzvjRE/KQawjLsbuNnYpI1SkjhwFqPOq58ec84nBo8ddarmMvwn9xkNiwzljxR4iXwATnJxogKewoIVj3smPr+Z7S7sjU6xOzwhktG5JWI1aISf65bRiu+7X6212JuN9grZIX/hQdPc8V0t4uj9OVk9ns=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
